import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Linking, Pressable, ScrollView, Text, View } from "react-native";

import { CivicDataPulse, IconTile, InfoCard, SectionHeader, SourceBadge } from "@/components/civic-ui";
import { ScreenContainer } from "@/components/screen-container";
import { serviceStateLabel, insightRoadmap } from "@/lib/service-intelligence";
import { trpc } from "@/lib/trpc";

export default function IntelligenceScreen() {
  const pulse = trpc.civic.servicePulse.useQuery(undefined, { staleTime: 60_000, retry: 1 });
  const insights = trpc.civic.insights.useQuery(undefined, { staleTime: 300_000, retry: 1 });
  const feeds = pulse.data?.feeds ?? [];
  const connectedCount = pulse.data?.sourceChecks.filter((source) => source.connected).length ?? 0;

  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 120 }}>
    <View className="flex-row items-center justify-between py-4"><View className="flex-1"><Text className="font-display text-2xl font-extrabold text-foreground">Civic intelligence</Text><Text className="mt-1 max-w-[310px] text-sm leading-5 text-muted">See the signals behind the service story — with the uncertainty left visible.</Text></View><View className="ml-3 h-11 w-11 items-center justify-center rounded-2xl bg-[#E9F2FF]"><MaterialIcons name="insights" size={23} color="#1F5EFF" /></View></View>
    <View className="rounded-[28px] p-5" style={{ backgroundColor: "#10243A" }}><View className="flex-row items-start justify-between"><View className="flex-1"><SourceBadge label="Connected civic layer" tone="civic" /><Text style={{ color: "#FFFFFF", fontFamily: "SpaceGrotesk_700Bold" }} className="mt-4 text-[27px] font-extrabold leading-8">From alerts to evidence.</Text><Text style={{ color: "#B7C9D9" }} className="mt-3 text-sm leading-5">CivicLens is beginning to connect place, service, money, and resident experience into one traceable picture.</Text></View><View className="ml-3 h-12 w-12 items-center justify-center rounded-2xl bg-[#203D5B]"><MaterialIcons name="hub" size={23} color="#A9C9FF" /></View></View><View className="mt-5 flex-row gap-2"><View className="flex-1 rounded-2xl bg-white/10 p-3"><Text style={{ color: "#B7C9D9" }} className="text-[10px] uppercase tracking-[1px]">Source coverage</Text><Text className="mt-1 text-xl font-extrabold text-white">{connectedCount}/3</Text></View><View className="flex-1 rounded-2xl bg-white/10 p-3"><Text style={{ color: "#B7C9D9" }} className="text-[10px] uppercase tracking-[1px]">Service domains</Text><Text className="mt-1 text-xl font-extrabold text-white">{feeds.length || 4}</Text></View></View></View>

    <View className="mt-7"><SectionHeader eyebrow="Live service pulse" title="What the connected sources say" action="Refresh" onAction={() => pulse.refetch()} /><View className="rounded-2xl border border-[#D8E5F5] bg-[#F5F9FF] p-3"><CivicDataPulse /><Text className="mt-2 text-[11px] leading-4 text-muted">This is a source monitor, not a claim that every ward is unaffected. Structured ward-level feeds are added as municipalities publish them.</Text></View><View className="mt-3 gap-2">{feeds.map((feed) => <View key={feed.id} className="rounded-[22px] border border-border bg-surface p-4"><View className="flex-row items-start gap-3"><IconTile icon={feed.icon} color={feed.accent} /><View className="flex-1"><View className="flex-row items-start justify-between gap-2"><Text className="text-base font-extrabold text-foreground">{feed.label}</Text><Text className="text-[10px] font-extrabold uppercase tracking-[.6px]" style={{ color: feed.state === "unknown" ? "#C94E4E" : "#A96D00" }}>{serviceStateLabel(feed.state)}</Text></View><Text className="mt-2 text-sm font-bold text-foreground">{feed.headline}</Text><Text className="mt-1 text-xs leading-4 text-muted">{feed.detail}</Text><View className="mt-3 flex-row items-center justify-between"><Text className="text-[10px] text-muted">{feed.sourceLabel}</Text><Pressable onPress={() => Linking.openURL(feed.sourceUrl)} style={({ pressed }) => pressed && { opacity: 0.7 }}><Text className="text-[10px] font-extrabold text-primary">Open source →</Text></Pressable></View></View></View></View>)}</View></View>

    <View className="mt-8"><SectionHeader eyebrow="Unseen insights, made practical" title="What connected data unlocks" /><View className="gap-3">{(insights.data?.insights ?? []).map((insight) => {insight.id === "triage" ? <Pressable key={insight.id} onPress={() => router.push("/(tabs)/report" as never)} style={({ pressed }) => pressed && { opacity: 0.75 }}><InfoCard> : <View key={insight.id}><View className="flex-row items-start gap-3"><IconTile icon={insight.icon} color={insight.accent} /><View className="flex-1"><Text className="text-[10px] font-extrabold uppercase tracking-[1.2px]" style={{ color: insight.accent }}>{insight.eyebrow}</Text><Text className="mt-2 text-base font-extrabold text-foreground">{insight.title}</Text><Text className="mt-1 text-sm leading-5 text-muted">{insight.detail}</Text><View className="mt-3 flex-row flex-wrap gap-1.5">{insight.datasets.map((dataset) => <View key={dataset} className="rounded-full bg-[#F1F5F7] px-2 py-1"><Text className="text-[10px] font-bold text-[#5B7084]">{dataset}</Text></View>)}</View><Text className="mt-3 text-xs font-extrabold text-primary">{insight.action} →</Text></View></View></InfoCard>{insight.id === "triage" ? null : null}</View>)}</View></View>

    <View className="mt-8"><SectionHeader eyebrow="Beyond the current platform" title="A credible path forward" /><View className="gap-2">{insightRoadmap.map((step, index) => <View key={step.phase} className="flex-row gap-3"><View className="items-center"><View className="h-8 w-8 items-center justify-center rounded-full bg-[#E9F2FF]"><Text className="text-xs font-extrabold text-primary">{index + 1}</Text></View>{index < insightRoadmap.length - 1 ? <View className="my-1 w-px flex-1 bg-[#D8E5F5]" /> : null}</View><View className="flex-1 pb-4"><Text className="text-[10px] font-extrabold uppercase tracking-[1.2px] text-primary">{step.phase}</Text><Text className="mt-1 text-base font-extrabold text-foreground">{step.title}</Text><Text className="mt-1 text-sm leading-5 text-muted">{step.detail}</Text></View></View>)}</View></View>

    <View className="mt-4 rounded-3xl border border-[#F1D9A6] bg-[#FFF9EA] p-4"><View className="flex-row items-start gap-3"><MaterialIcons name="shield" size={21} color="#A96D00" /><Text className="flex-1 text-xs leading-5 text-[#795715]">Civic intelligence should reveal patterns, not manufacture certainty. Every future signal needs a source, timestamp, geography, confidence label, and a human-readable explanation.</Text></View></View>
  </ScrollView></ScreenContainer>;
}
