import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { FlatList, Linking, Pressable, ScrollView, Text, View } from "react-native";

import { Chip, IconTile, InfoCard, SectionHeader, SourceBadge } from "@/components/civic-ui";
import { ScreenContainer } from "@/components/screen-container";
import { communityIssues, financeTopics, notices } from "@/lib/civic-data";

export default function CommunityScreen() {
  return (
    <ScreenContainer className="px-5" containerClassName="bg-background">
      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 120 }}>
        <View className="py-4"><Text className="font-display text-2xl font-extrabold text-foreground">My community</Text><Text className="mt-1 text-sm leading-5 text-muted">A safer, clearer view of civic activity around you.</Text></View>
        <View className="overflow-hidden rounded-[28px] p-4" style={{ backgroundColor: "#DCE9EE" }}><View className="h-44 rounded-2xl" style={{ backgroundColor: "#C4D8DE" }}><View className="absolute left-[-20%] top-12 h-4 w-[150%] rotate-[16deg]" style={{ backgroundColor: "#EDF6F4" }} /><View className="absolute left-[-15%] top-28 h-3 w-[145%] rotate-[-20deg]" style={{ backgroundColor: "#EDF6F4" }} /><View className="absolute left-12 top-8 h-5 w-32 rotate-[-28deg]" style={{ backgroundColor: "#B3CDD2" }} /><View className="absolute right-8 top-24 h-5 w-28 rotate-[30deg]" style={{ backgroundColor: "#B3CDD2" }} /><View className="absolute left-[33%] top-[42%] h-12 w-12 items-center justify-center rounded-full border-4 border-white" style={{ backgroundColor: "#D9E6FF" }}><View className="h-4 w-4 rounded-full bg-primary" /></View><View className="absolute bottom-3 left-3 flex-row items-center gap-1 rounded-full bg-white/90 px-2 py-1"><MaterialIcons name="lock-outline" size={12} color="#59636E" /><Text className="text-[10px] font-bold text-[#59636E]">Area-level privacy view</Text></View></View><Text className="mt-3 text-sm font-extrabold text-[#11243B]">Soshanguve · City of Tshwane</Text><Text className="mt-1 text-xs leading-4 text-[#52677C]">Exact household locations, private evidence and reporter identities are not shown publicly.</Text></View>
        <View className="mt-5 flex-row gap-2"><Chip label="Issues" active /><Chip label="Projects" /><Chip label="Notices" onPress={() => Linking.openURL("https://www.gov.za/news/media-statements")} /><Chip label="Facilities" onPress={() => Linking.openURL("https://www.gov.za/about-government/contact-directory")} /></View>

        <View className="mt-7"><SectionHeader eyebrow="Community signals" title="What people are seeing" /></View>
        <FlatList data={communityIssues} scrollEnabled={false} keyExtractor={(item) => item.id} contentContainerStyle={{ gap: 9 }} renderItem={({ item }) => <Pressable style={({ pressed }) => pressed && { opacity: 0.72 }}><InfoCard><View className="flex-row items-start gap-3"><IconTile icon={item.status === "Planned" ? "construction" : item.status === "In progress" ? "delete-outline" : "lightbulb-outline"} color={item.tone === "success" ? "#27AE60" : item.tone === "warning" ? "#B27A00" : "#1769FF"} /><View className="flex-1"><View className="flex-row items-start justify-between gap-2"><Text className="flex-1 text-sm font-extrabold text-foreground">{item.title}</Text><SourceBadge label={item.tone === "warning" ? "Community" : item.tone === "success" ? "Official" : "CivicLens"} tone={item.tone === "warning" ? "community" : item.tone === "success" ? "official" : "civic"} /></View><Text className="mt-1 text-xs text-muted">{item.area}</Text><View className="mt-3 flex-row items-center justify-between"><Text className="text-xs font-bold text-foreground">{item.count}</Text><Text className="text-xs font-bold text-primary">{item.status} →</Text></View></View></View></InfoCard></Pressable>} />

        <View className="mt-7"><SectionHeader eyebrow="Participate" title="Public notices near you" action="Open official notices" onAction={() => Linking.openURL("https://www.gov.za/news/media-statements")} /></View>
        <FlatList data={notices} scrollEnabled={false} keyExtractor={(item) => item.id} contentContainerStyle={{ gap: 8 }} renderItem={({ item }) => <View className="flex-row items-center gap-3 rounded-2xl border border-border bg-surface p-3"><IconTile icon={item.icon} color="#1769FF" size="small" /><View className="flex-1"><Text className="text-[10px] font-extrabold uppercase tracking-[1px] text-primary">{item.type}</Text><Text className="mt-1 text-sm font-extrabold text-foreground">{item.title}</Text><Text className="mt-1 text-xs text-muted">{item.detail}</Text><Text className="mt-2 text-[11px] font-bold text-[#9A6B00]">{item.deadline}</Text></View><MaterialIcons name="chevron-right" size={19} color="#9AA5B1" /></View>} />

        <View className="mt-7"><SectionHeader eyebrow="Follow the money" title="Municipal finance, explained" /></View>
        <InfoCard><View className="flex-row items-start justify-between"><View className="flex-1"><SourceBadge label="National Treasury dataset" tone="official" /><Text className="mt-3 text-lg font-extrabold text-foreground">City of Tshwane snapshot</Text><Text className="mt-1 text-sm leading-5 text-muted">See how the municipality earns, spends and maintains services without accounting jargon.</Text></View><View className="h-12 w-12 items-center justify-center rounded-2xl bg-[#E8F7EE]"><MaterialIcons name="insights" size={23} color="#27AE60" /></View></View><View className="mt-4 flex-row gap-2">{financeTopics.map((topic) => <View key={topic.label} className="flex-1 items-center rounded-2xl bg-background px-2 py-3"><IconTile icon={topic.icon} color="#27AE60" size="small" /><Text className="mt-2 text-center text-[10px] font-bold leading-3 text-foreground">{topic.label}</Text></View>)}</View><Text className="mt-4 text-[11px] leading-4 text-muted">Figures are source-derived and may be updated as submissions are verified. Open the dataset to see the reporting period and limitations.</Text></InfoCard>

        <View className="mt-7 rounded-3xl border border-[#D8E5F5] bg-[#F5F9FF] p-4"><View className="flex-row gap-3"><IconTile icon="info-outline" color="#1769FF" /><View className="flex-1"><Text className="text-sm font-extrabold text-[#11243B]">Community is not official confirmation</Text><Text className="mt-1 text-xs leading-4 text-[#5B7084]">CivicLens keeps community reports, official responses and CivicLens interpretation visibly distinct.</Text></View></View></View>
      </ScrollView>
    </ScreenContainer>
  );
}
