import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { FlatList, Pressable, ScrollView, Text, View } from "react-native";

import { ActionButton, CivicDataPulse, CivicMark, IconTile, InfoCard, SectionHeader, SourceBadge, TrustStrip } from "@/components/civic-ui";
import { ScreenContainer } from "@/components/screen-container";
import { issueCategories, lessons, notices } from "@/lib/civic-data";
import { useCivic } from "@/lib/civic-store";

export default function HomeScreen() {
  const { cases, selectedLocation } = useCivic();
  const openCases = cases.filter((item) => !["Resolved", "Closed"].includes(item.status)).length;
  const go = (path: string) => router.push(path as never);
  const wardLabel = selectedLocation.wardNumber ? `Ward ${selectedLocation.wardNumber}` : "Ward not selected";

  return (
    <ScreenContainer className="px-5" containerClassName="bg-background">
      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 34 }}>
        <View className="flex-row items-center justify-between py-4">
          <View className="flex-row items-center gap-3"><CivicMark compact /><View><Text className="font-display text-lg font-extrabold tracking-tight text-foreground">CivicLens</Text><Text className="text-[10px] font-bold uppercase tracking-[1.5px] text-muted">South Africa</Text></View></View>
          <View className="flex-row items-center gap-2"><CivicDataPulse compact /><Pressable accessibilityLabel="Notifications" style={({ pressed }) => pressed && { opacity: 0.6 }}><View className="h-10 w-10 items-center justify-center rounded-full border border-border bg-surface"><MaterialIcons name="notifications-none" size={21} color="#59636E" /></View></Pressable></View>
        </View>

        <View className="overflow-hidden rounded-[30px] p-6" style={{ backgroundColor: "#0B2030" }}>
          <View className="absolute -right-10 -top-12 h-40 w-40 rounded-full border-[20px] border-[#173B58]" /><View className="absolute -bottom-16 -right-5 h-36 w-36 rounded-full border-[14px] border-[#16364F]" />
          <View className="flex-row items-center justify-between"><SourceBadge label="Your civic command centre" tone="civic" /><View className="rounded-full bg-white/10 px-2.5 py-1"><Text className="text-[10px] font-extrabold uppercase tracking-[1px] text-[#B9D5FF]">Today</Text></View></View>
          <Text style={{ color: "#FFFFFF", fontFamily: "SpaceGrotesk_700Bold" }} className="mt-5 max-w-[310px] text-[31px] font-extrabold leading-9">Make your next civic move count.</Text>
          <Text style={{ color: "#B8C9D8", fontFamily: "Inter_400Regular" }} className="mt-3 max-w-[315px] text-sm leading-5">Report with confidence, reach the right office, and keep a clear record from first signal to resolution.</Text>
          <View className="mt-5 flex-row gap-3"><ActionButton label="Start a report" icon="add" onPress={() => go("/(tabs)/report")} /><ActionButton label="Government" icon="account-balance" variant="secondary" onPress={() => go("/(tabs)/government")} /></View>
        </View>

        <View className="mt-4 rounded-[24px] border border-[#CFE0FF] bg-[#F4F8FF] p-4"><View className="flex-row items-center gap-3"><View className="h-10 w-10 items-center justify-center rounded-[14px] bg-[#DCE9FF]"><MaterialIcons name="location-on" size={20} color="#1F5EFF" /></View><View className="flex-1"><Text className="text-[10px] font-extrabold uppercase tracking-[1.3px] text-primary">Your civic profile</Text><Text className="mt-1 text-base font-extrabold text-foreground">{selectedLocation.name}</Text><Text className="mt-1 text-xs text-muted">{wardLabel} · {selectedLocation.province}</Text></View><Pressable onPress={() => go("/(tabs)/government")} style={({ pressed }) => pressed && { opacity: 0.6 }}><MaterialIcons name="edit" size={17} color="#1F5EFF" /></Pressable></View><View className="mt-3 flex-row items-center justify-between border-t border-[#DCE8F6] pt-3"><Text className="text-[11px] font-semibold text-muted">{selectedLocation.wardNumber ? "Precise routing enabled" : "Choose a ward for precise routing"}</Text><Text className="text-[11px] font-extrabold text-primary">{selectedLocation.code}</Text></View></View>

        <View className="mt-4 flex-row gap-3"><Pressable onPress={() => go("/(tabs)/cases")} className="flex-1"><InfoCard><Text className="text-[10px] font-extrabold uppercase tracking-[1px] text-primary">Case engine</Text><Text className="mt-1 text-base font-extrabold text-foreground">{openCases} active case{openCases===1?"":"s"}</Text><Text className="mt-1 text-xs leading-4 text-muted">Track your private timeline</Text></InfoCard></Pressable><Pressable onPress={() => go("/(tabs)/government")} className="flex-1"><InfoCard><Text className="text-[10px] font-extrabold uppercase tracking-[1px] text-primary">Routing</Text><Text className="mt-1 text-base font-extrabold text-foreground">{wardLabel}</Text><Text className="mt-1 text-xs leading-4 text-muted">Improve local routing</Text></InfoCard></Pressable></View><View className="mt-8"><SectionHeader eyebrow="Start with your situation" title="What needs attention?" action="Browse all" onAction={() => go("/(tabs)/report")} /><FlatList data={issueCategories.slice(0, 4)} numColumns={2} scrollEnabled={false} columnWrapperStyle={{ gap: 10 }} contentContainerStyle={{ gap: 10 }} keyExtractor={(item) => item.id} renderItem={({ item }) => <Pressable onPress={() => go("/(tabs)/report")} style={({ pressed }) => [{ flex: 1 }, pressed && { opacity: 0.72 }]}><View className="rounded-[22px] border border-border bg-surface p-4"><IconTile icon={item.icon} color={item.accent} size="small" /><Text className="mt-3 text-sm font-extrabold text-foreground">{item.label}</Text><Text className="mt-1 text-xs leading-4 text-muted" numberOfLines={2}>{item.hint}</Text></View></Pressable>} /></View>

        <View className="mt-8"><SectionHeader eyebrow="Connected civic brief" title="What is true around you?" /><View className="rounded-[26px] p-5" style={{ backgroundColor: "#102A3E" }}><View className="flex-row items-start justify-between"><View className="flex-1"><Text className="text-[10px] font-extrabold uppercase tracking-[1.4px] text-[#A9C9FF]">Official location signal</Text><Text className="mt-2 font-display text-xl font-extrabold text-white">{selectedLocation.name}</Text><Text className="mt-1 text-sm text-[#B8C9D8]">{selectedLocation.district} · {selectedLocation.province}</Text></View><View className="h-12 w-12 items-center justify-center rounded-2xl bg-[#1B4564]"><MaterialIcons name="verified" size={23} color="#A9C9FF" /></View></View><View className="mt-5 flex-row gap-2"><View className="flex-1 rounded-2xl bg-white/10 p-3"><Text className="text-[10px] uppercase tracking-[1px] text-[#B8C9D8]">Ward</Text><Text className="mt-1 text-sm font-extrabold text-white">{selectedLocation.wardNumber ? `#${selectedLocation.wardNumber}` : "Select"}</Text></View><View className="flex-1 rounded-2xl bg-white/10 p-3"><Text className="text-[10px] uppercase tracking-[1px] text-[#B8C9D8]">Routing</Text><Text className="mt-1 text-sm font-extrabold text-white">{selectedLocation.wardNumber ? "Precise" : "Municipal"}</Text></View></View><Pressable onPress={() => go("/directory")} style={({ pressed }) => pressed && { opacity: 0.7 }}><Text className="mt-4 text-xs font-extrabold text-[#A9C9FF]">Open official civic directory →</Text></Pressable></View></View>

        <Pressable onPress={() => go("/intelligence")} style={({ pressed }) => pressed && { opacity: 0.75 }}><View className="mt-3 flex-row items-center gap-3 rounded-[24px] border border-[#D7E5FF] bg-[#F4F8FF] p-4"><View className="h-11 w-11 items-center justify-center rounded-2xl bg-[#DCE9FF]"><MaterialIcons name="insights" size={22} color="#1F5EFF" /></View><View className="flex-1"><Text className="text-[10px] font-extrabold uppercase tracking-[1.2px] text-primary">Beyond the dashboard</Text><Text className="mt-1 text-base font-extrabold text-foreground">Open Civic Intelligence</Text><Text className="mt-1 text-xs leading-4 text-muted">See live service pulse, source coverage, and what connected data can reveal.</Text></View><MaterialIcons name="arrow-forward" size={20} color="#1F5EFF" /></View></Pressable>

        <View className="mt-8"><SectionHeader eyebrow="Learn in plain language" title="One useful idea, right now" action="Explore learn" onAction={() => go("/(tabs)/learn")} /><Pressable onPress={() => go("/(tabs)/learn")} style={({ pressed }) => pressed && { opacity: 0.75 }}><InfoCard><View className="flex-row gap-3"><IconTile icon={lessons[0].icon} color="#7B61FF" /><View className="flex-1"><View className="flex-row items-center justify-between"><Text className="text-xs font-bold text-primary">{lessons[0].category}</Text><Text className="text-xs font-semibold text-muted">{lessons[0].length}</Text></View><Text className="mt-2 text-base font-extrabold text-foreground">{lessons[0].title}</Text><Text className="mt-1 text-sm leading-5 text-muted">{lessons[0].summary}</Text></View></View></InfoCard></Pressable></View>

        <View className="mt-8"><SectionHeader eyebrow="Participation" title="Your next civic signal" />{notices.slice(0, 2).map((notice) => <View key={notice.id} className="mb-2 flex-row items-center gap-3 rounded-2xl border border-border bg-surface p-3"><IconTile icon={notice.icon} color="#1769FF" size="small" /><View className="flex-1"><Text className="text-sm font-extrabold text-foreground">{notice.title}</Text><Text className="mt-1 text-xs text-muted">{notice.deadline}</Text></View><MaterialIcons name="chevron-right" size={20} color="#9AA5B1" /></View>)}</View>

        <View className="mt-6"><TrustStrip/></View><View className="mt-7 rounded-3xl border border-[#D8E5F5] bg-[#F5F9FF] p-4"><View className="flex-row items-start gap-3"><View className="h-10 w-10 items-center justify-center rounded-2xl bg-[#DDEBFF]"><MaterialIcons name="verified" size={21} color="#1769FF" /></View><View className="flex-1"><Text className="text-base font-extrabold text-[#11243B]">Trust is part of the product</Text><Text className="mt-1 text-sm leading-5 text-[#5B7084]">Official records stay labelled, community signals stay distinct, and connected sources show when they were last checked.</Text><View className="mt-3"><CivicDataPulse /></View></View></View></View>
      </ScrollView>
    </ScreenContainer>
  );
}
